keycloak:
  server-ul: https://keycloak.code-factory.co.kr
  realm: codefactory
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  amin-password: ${KEYCLOAK_ADMIN_PASSWORD}